# -*- coding: utf-8 -*-
"""task-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WDtpdVkLLSg0LzYe-73dRsCC8cSOLCzb

### **Task-01**
Create a bar chart or histogram to visualize the distribution of a categorical or continuous variable, such as the distribution of ages or genders in a population.
"""

import matplotlib.pyplot as plt

gender_data = ['Male', 'Female', 'Female', 'Male', 'Male', 'Other', 'Female', 'Female', 'Male', 'Other']

from collections import Counter
gender_counts = Counter(gender_data)

plt.figure(figsize=(6,4))
plt.bar(gender_counts.keys(), gender_counts.values(), color=['skyblue', 'pink', 'gray'])
plt.title('Gender Distribution')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

import matplotlib.pyplot as plt

age_data = [23, 25, 22, 30, 29, 31, 35, 25, 27, 30, 34, 22, 28, 26, 27]

plt.figure(figsize=(6,4))
plt.hist(age_data, bins=5, color='purple', edgecolor='black')
plt.title('Age Distribution')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()